const OTP_VERIFICATION_TYPE_ENUMS = {
  VERIFICATION: 'V',
  EMAIL: 'E',
  LOGIN: 'L',
  REGISTER: 'R'
}

const OTP_VERIFICATION_PLATFORM_ENUMS = {
  MOBILE: 'M',
  EMAIL: 'E'
}

module.exports = {
  OTP_VERIFICATION_TYPE_ENUMS,
  OTP_VERIFICATION_PLATFORM_ENUMS
}
